apiVersion: apps/v1
kind: Deployment
metadata:
  name: wowza-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wowza
  template:
    metadata:
      labels:
        app: wowza
    spec:
      containers:
      - name: wowza
        image: wowzamedia/wowza-streaming-engine-linux:latest
        command: ["/bin/sh", "-c", "/sbin/entrypoint.sh"]
        ports:
        - containerPort: 1935 # Streaming port
        - containerPort: 8088 # Manager log
        env:
        - name: WSE_LIC
          value: "ET1B4-TTEpx-CGJHA-zHHvy-63KzG-P6RAp-47UeyP7mNvWp" # License key
        - name: WSE_MGR_USER
          value: "admin" # Username
        - name: WSE_MGR_PASS
          value: "password" # Password
        volumeMounts:
        - name: wowza-vod-application-configmap
          mountPath: /usr/local/WowzaStreamingEngine/conf/vod/Application.xml
          subPath: Application.xml
        - name: wowza-content-volume
          mountPath: /usr/local/WowzaStreamingEngine/content
        - name: wowza-log-volume
          mountPath: /usr/local/WowzaStreamingEngine/logs
        - name: wowza-manager-log-volume
          mountPath: /usr/local/WowzaStreamingEngine/manager/logs
      volumes:
      - name: wowza-vod-application-configmap
        configMap:
          name: wowza-vod-application-configmap
      - name: wowza-content-volume
        hostPath:
          path: /wowza/content # Set the media storage
          type: Directory
      - name: wowza-log-volume
        hostPath:
          path: /wowza/wowza-log-volume # Set the logs storage
          type: Directory
      - name: wowza-manager-log-volume
        hostPath:
          path: /wowza/wowza-manager-log-volume # Set the manager logs storage
          type: Directory